table Trips
	lineageTag: a81d849c-0fa8-4fd7-b42b-0e70b73f312a

	column trip_id
		dataType: int64
		formatString: 0
		lineageTag: 81097488-6962-4c69-aced-500cdeee6c28
		summarizeBy: none
		sourceColumn: trip_id

		annotation SummarizationSetBy = Automatic

	column rider_id
		dataType: int64
		formatString: 0
		lineageTag: 4027198a-3717-46e3-a327-c85056096ef2
		summarizeBy: none
		sourceColumn: rider_id

		annotation SummarizationSetBy = Automatic

	column driver_id
		dataType: int64
		formatString: 0
		lineageTag: 075459a6-0429-4bfc-9e13-a9fda74ae100
		summarizeBy: none
		sourceColumn: driver_id

		annotation SummarizationSetBy = Automatic

	column request_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 5708274d-a32f-4856-a0ba-95940fd14cc6
		summarizeBy: none
		sourceColumn: request_datetime

		annotation SummarizationSetBy = Automatic

	column distance_km
		dataType: double
		formatString: 0.00
		lineageTag: 351ccbe4-8752-4797-9e2b-a24554408dd7
		summarizeBy: none
		sourceColumn: distance_km

		annotation SummarizationSetBy = Automatic

	column duration_min
		dataType: double
		formatString: 0.0
		lineageTag: 6447be0c-55f3-45c4-bdf9-170707edec1a
		summarizeBy: none
		sourceColumn: duration_min

		annotation SummarizationSetBy = Automatic

	column fare_amount
		dataType: double
		formatString: "₹"#,0.00
		lineageTag: 2a87f6ea-2810-464d-9469-719bddb89dfe
		summarizeBy: none
		sourceColumn: fare_amount

		annotation SummarizationSetBy = Automatic

	column surge_multiplier
		dataType: double
		formatString: 0.00
		lineageTag: 2ca10fbb-ab0a-4b97-badd-bbcf346c04ba
		summarizeBy: none
		sourceColumn: surge_multiplier

		annotation SummarizationSetBy = Automatic

	column trip_status
		dataType: string
		lineageTag: 654e0875-ec0c-443f-9343-c2f08fb77d8d
		summarizeBy: none
		sourceColumn: trip_status

		annotation SummarizationSetBy = Automatic

	column cancellation_reason
		dataType: string
		lineageTag: a8bb368a-eca6-4be2-ae8a-b1ee511215b4
		summarizeBy: none
		sourceColumn: cancellation_reason

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: 586b9036-eeb8-4e80-a545-79a30c363d00
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column vehicle_type
		dataType: string
		lineageTag: 060a44f5-ee30-4925-a4bc-7159bbe97704
		summarizeBy: none
		sourceColumn: vehicle_type

		annotation SummarizationSetBy = Automatic

	column pickup_city
		dataType: string
		lineageTag: 905cb399-715a-463d-8ea5-ea0df15d437b
		summarizeBy: none
		sourceColumn: pickup_city

		annotation SummarizationSetBy = Automatic

	column drop_city
		dataType: string
		lineageTag: 177720bc-985e-441e-b07e-01d7995d048b
		summarizeBy: none
		sourceColumn: drop_city

		annotation SummarizationSetBy = Automatic

	column driver_avg_rating
		dataType: double
		formatString: 0.00
		lineageTag: d87df9fb-8c2b-44de-a859-8d29e5bcde0c
		summarizeBy: none
		sourceColumn: driver_avg_rating

		annotation SummarizationSetBy = Automatic

	column driver_rating_for_rider
		dataType: double
		formatString: 0.0
		lineageTag: b4cb6e34-700e-4553-8cfe-20bca630c74d
		summarizeBy: none
		sourceColumn: driver_rating_for_rider

		annotation SummarizationSetBy = Automatic

	column request_hour
		dataType: int64
		formatString: 0
		lineageTag: d72dab25-b7d3-4413-aa9e-59e7670f3e73
		summarizeBy: none
		sourceColumn: request_hour

		annotation SummarizationSetBy = Automatic

	column request_dow
		dataType: int64
		formatString: 0
		lineageTag: 379d85d1-da76-4476-8e7c-a5c500de7018
		summarizeBy: none
		sourceColumn: request_dow

		annotation SummarizationSetBy = Automatic

	column request_day
		dataType: string
		lineageTag: 7cf6af43-b1e6-4ef0-b671-28b04535005b
		summarizeBy: none
		sourceColumn: request_day

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: ec2a2426-1e34-465b-a9d2-048afb1db008
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_peak_hour
		dataType: int64
		formatString: 0
		lineageTag: 1f22b4d3-d3c2-497d-b976-bc20ffa14cf1
		summarizeBy: none
		sourceColumn: is_peak_hour

		annotation SummarizationSetBy = Automatic

	column is_cancelled
		dataType: int64
		formatString: 0
		lineageTag: 74c3d640-581d-4199-8cbb-6bcc9222c841
		summarizeBy: none
		sourceColumn: is_cancelled

		annotation SummarizationSetBy = Automatic

	column fare_per_km
		dataType: double
		formatString: 0.00
		lineageTag: 45667b23-1331-491b-9819-09597bf12bcc
		summarizeBy: none
		sourceColumn: fare_per_km

		annotation SummarizationSetBy = Automatic

	measure 'Total Trips' = COUNTROWS(Trips)
		formatString: #,0
		lineageTag: 3c1249cf-ce16-4260-ba1b-643ffb01129a

	measure 'Completed Trips' = CALCULATE(COUNTROWS(Trips), Trips[trip_status] = "Completed")
		formatString: #,0
		lineageTag: c16f3fed-4dd2-4192-a1ba-29f66eb6c304

	measure 'Cancelled Trips' = CALCULATE(COUNTROWS(Trips), Trips[is_cancelled] = 1)
		formatString: #,0
		lineageTag: 921b0993-5967-46cd-a4a3-6eaf4868b277

	measure 'Cancellation Rate' = DIVIDE([Cancelled Trips], [Total Trips])
		formatString: 0.0%
		lineageTag: 867102ca-6f04-45e5-a7b4-fcbf121fd260

	measure 'Total Revenue' = CALCULATE(SUM(Trips[fare_amount]), Trips[trip_status] = "Completed")
		formatString: "₹"#,0
		lineageTag: 5b464b0b-cd55-43b4-9baf-c4b270365680

	measure 'Average Fare' = CALCULATE(AVERAGE(Trips[fare_amount]), Trips[trip_status] = "Completed")
		formatString: "₹"#,0.00
		lineageTag: b901e8c6-0233-4873-b019-fd8d978b616e

	measure 'Average Distance (km)' = CALCULATE(AVERAGE(Trips[distance_km]), Trips[trip_status] = "Completed")
		formatString: 0.00
		lineageTag: ea7c29e2-9fe6-48dd-bed6-1170f18866e7

	measure 'Average Duration (min)' = CALCULATE(AVERAGE(Trips[duration_min]), Trips[trip_status] = "Completed")
		formatString: 0.0
		lineageTag: 85877c9b-8284-4dab-9478-8e845aadd809

	measure 'Fare per KM' = DIVIDE([Total Revenue], CALCULATE(SUM(Trips[distance_km]), Trips[trip_status] = "Completed"))
		formatString: "₹"#,0.00
		lineageTag: 569160a6-45c2-4107-961e-51545ecf8d7e

	measure 'Active Riders' = DISTINCTCOUNT(Trips[rider_id])
		formatString: #,0
		lineageTag: f5b5b0cd-ba71-4dbf-9374-d6845b9b75d4

	measure 'Active Drivers' = DISTINCTCOUNT(Trips[driver_id])
		formatString: #,0
		lineageTag: ad21d8f6-6318-4168-9242-059ccf386162

	measure 'Trips per Rider' = DIVIDE([Total Trips], [Active Riders])
		formatString: 0.00
		lineageTag: 5bfcf189-94a6-408c-9901-860c1aff93b1

	measure 'Trips per Driver' = DIVIDE([Total Trips], [Active Drivers])
		formatString: 0.00
		lineageTag: ae7a4337-db9a-4d3d-9ae0-9674b4d1e56c

	measure 'Revenue per Driver' = DIVIDE([Total Revenue], [Active Drivers])
		formatString: "₹"#,0
		lineageTag: 015b1d14-2de6-471a-a704-ef371de57141

	measure 'Average Rating' = CALCULATE(AVERAGE(Trips[driver_rating_for_rider]), Trips[trip_status] = "Completed")
		formatString: 0.00
		lineageTag: 9d91be74-bc64-4fba-8b81-f99d68eece25

	partition Trips = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRootPath & "\data\processed\trips_analysis_ready.csv"), [Delimiter=",", Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					SelectedColumns = Table.SelectColumns(PromotedHeaders, {"trip_id", "rider_id", "driver_id", "request_datetime", "distance_km", "duration_min", "fare_amount", "surge_multiplier", "trip_status", "cancellation_reason", "payment_method", "vehicle_type", "pickup_city", "drop_city", "driver_avg_rating", "driver_rating_for_rider", "request_hour", "request_dow", "request_day", "is_weekend", "is_peak_hour", "is_cancelled", "fare_per_km"}),
					ChangedType = Table.TransformColumnTypes(SelectedColumns, {{"trip_id", Int64.Type}, {"rider_id", Int64.Type}, {"driver_id", Int64.Type}, {"request_datetime", type datetime}, {"distance_km", type number}, {"duration_min", type number}, {"fare_amount", type number}, {"surge_multiplier", type number}, {"trip_status", type text}, {"cancellation_reason", type text}, {"payment_method", type text}, {"vehicle_type", type text}, {"pickup_city", type text}, {"drop_city", type text}, {"driver_avg_rating", type number}, {"driver_rating_for_rider", type number}, {"request_hour", Int64.Type}, {"request_dow", Int64.Type}, {"request_day", type text}, {"is_weekend", Int64.Type}, {"is_peak_hour", Int64.Type}, {"is_cancelled", Int64.Type}, {"fare_per_km", type number}})
				in
					ChangedType

	annotation PBI_ResultType = Table
